INSERT INTO Cualitativa 
    (contenido, idPregunta, idRetroalimentacion) 
VALUES
-- ¿Qué hicimos bien este Sprint?
    ('Mantener una comunicación constante entre todos los miembros del equipo.', 4, 1),
    ('Ayudamos todos entre todos', 4, 3),
    ('Logramos completar todas las tareas planificadas para este Sprint en el plazo previsto.', 4, 1),
    ('Hicimos un gran progreso en el desarrollo de nuevas características para el producto.', 4, 1),
    ('Realizamos pruebas exhaustivas en cada tarea y nos aseguramos de que todo funcionara correctamente.', 4, 3),
    ('Implementamos nuevas herramientas o tecnologías que nos permitieron mejorar la calidad o la eficiencia de nuestro trabajo.', 4, 2),
    ('Nos comunicamos de manera efectiva con el cliente o el equipo de dirección para obtener retroalimentación y asegurarnos de estar en el mismo camino.', 4, 2),
    ('Logramos solucionar problemas difíciles que surgieron durante el Sprint de manera eficiente y efectiva.', 4, 2),
    ('Hicimos un excelente trabajo en la documentación y el registro de nuestro trabajo para futuras referencias.', 4, 2),
    ('Conseguimos mejorar la calidad de nuestro código y reducir el número de errores.', 4, 2),
    ('Mantuvimos una buena gestión del tiempo y la productividad durante todo el Sprint.', 4, 2),
    ('Mejoramos la coordinación con otros equipos que dependen de nuestro trabajo.', 4, 3),
    ('Realizamos una excelente planificación y organización de nuestras tareas para garantizar la eficiencia del equipo.', 4, 3),
    ('Realizamos una buena revisión y mejora continua del trabajo realizado en este Sprint.', 4, 1),
-- ¿Qué hicimos mal que debemos hacer diferente?
    ('No esperar hasta el último momento donde se amontonan las cosas.', 5, 2),
    ('No comunicarnos adecuadamente.', 5, 2),
    ('No tomar suficiente tiempo para reflexionar.', 5, 2),
    ('No ser proactivos.', 5, 1),
    ('No escuchar a los demás.', 5, 2),
    ('No ser organizados.', 5, 1),
    ('No aprender de nuestros errores.', 5, 1),
    ('No establecer objetivos claros y medibles.', 5, 1),
    ('No ser perseverantes en nuestros esfuerzos.', 5, 3),
    ('No tener un plan de acción bien definido.', 5, 2),
    ('No delegar tareas de manera efectiva.', 5, 3),
    ('No tener en cuenta las opiniones de los clientes.', 5, 3),
    ('No ser flexibles ante cambios y nuevos desafíos.', 5, 3),
    ('No dar suficiente importancia al trabajo en equipo.', 5, 1),
-- ¿Qué nos causa ruido?
    ('Injusta distribución de trabajos', 6, 2),
    ('Interrupciones frecuentes en forma de llamadas telefónicas o correos electrónicos.', 6, 2),
    ('Problemas técnicos con la herramienta de trabajo utilizada.', 6, 1),
    ('La falta de claridad en los requisitos del proyecto.', 6, 1),
    ('Los cambios frecuentes en los requisitos del proyecto.', 6, 1),
    ('La falta de recursos para completar las tareas asignadas.', 6, 1),
    ('Las reuniones prolongadas que interrumpieron la productividad.', 6, 3),
    ('La falta de retroalimentación o comunicación efectiva del equipo de liderazgo.', 6, 3),
    ('Las distracciones en el entorno de trabajo, como ruido de fondo o ruido de construcción cercana.', 6, 3),
    ('Los problemas con el flujo de trabajo y la organización del equipo.', 6, 1),
    ('Las discrepancias en las expectativas del equipo y la gestión del proyecto.', 6, 2),
    ('Los problemas con el equipo, como fallas técnicas o conflictos interpersonales', 6, 2),
    ('La falta de habilidades o experiencia en el equipo para llevar a cabo algunas tareas.', 6, 2),
    ('Los cambios de prioridad frecuentes que dificultaron la planificación y el progreso del proyecto.', 6, 1),
-- ¿Qué impedimiento tuvimos en este Sprint?
    ('Un integrante del equipo estuvo muy perdido durante todo el Sprint.', 7, 1),
    ('Problemas con la infraestructura de la red', 7, 2),
    ('Interrupciones constantes en el trabajo', 7, 3),
    ('Retrasos en la entrega de las tareas asignadas', 7, 1),
    ('Falta de claridad en las expectativas del proyecto', 7, 1),
    ('Problemas de compatibilidad de software', 7, 2),
    ('Cambios frecuentes en los requisitos del proyecto', 7, 2),
    ('Ausencia de un líder de proyecto efectivo', 7, 2),
    ('Falta de recursos adecuados', 7, 3),
    ('Incapacidad para alcanzar los objetivos de calidad', 7, 3),
    ('Conflictos entre los miembros del equipo', 7, 3),
    ('Falta de motivación de los miembros del equipo', 7, 2),
    ('Falta de experiencia en el trabajo asignado', 7, 1),
    ('Problemas de gestión del tiempo', 7, 1),
-- ¿Qué podemos mejorar?
    ('Para que todos los miembros del equipo se sientan unidos entre todos, tendríamos que hacer una noche de Pizza', 8, 3),
    ('Establecer una reunión diaria para el equipo para discutir el progreso y cualquier problema que surja.', 8, 2),
    ('Proporcionar una capacitación adicional al equipo para desarrollar habilidades específicas que puedan mejorar la calidad del trabajo.', 8, 2),
    ('Celebrar los éxitos y los hitos alcanzados durante el Sprint para mantener al euqipo motivado y comprometido con el proyecto dando premios', 8, 1),
    ('Asignar un líder de equipo o un responsable de proyecto para asegurarse de que el trabajo se organice y se realice de manera efectiva', 8, 3),
    ('Tener sesiones para compartir nuestra experiencia para proporcionar apoyo emocional y profesional al equipo para manejar el estrés y las presiones del proyecto', 8, 1),
    ('Establecer un plan de contigencia para manejar cualquier imprevisto o contratiempo durante el Sprint', 8, 2),
    ('Asignar responsabilidades y tareas específicas a cada miembro del equipo para evitar duplicidad de esfuerzos', 8, 2),
    ('Asegurars ede que los miembros del equ9po estén capacitados en las herramientas y tecnologías necesarias para el proyecto', 8, 1),
    ('Promover una cultura de aprendizaje continuo, fomentando la capacitación y el desarrollo personal y profesional del equipo.', 8, 3),
    ('Evaluar y revisar el éxito del Sprint al final de una Épia para identificar áreas de mejora y aplicarlas en proyectos futuros', 8, 1),
    ('Revisar y mejorar los procesos de colaboración para fomentar la creatividad y la innovación en el equipo.', 8, 3),
    ('Tener sesiones de retroalimentación individual para revisar desempeño de cada uno', 8, 1),
    ('Para que todos puedan energía mientras que trabajamos, tener un Snack Bar en la oficina', 8, 1);

   